### ISSUE TITLE
What is it?

### ISSUE THREAD

**Issue by lorenzomassacci** [e-xtrategy/architectural-clash#1]
Will It be a format similar to coderetreat but specific about software architecture?

**Comment by francesco-strazzullo** [comment]
The purpose will be similar, but the execution it's quite different. You will have a whole team for a medium period (2 days for example) that tries to achieve an impossible task. As I said before the purpose it's the same of a retreat: _to learn_. In a retreat you learn by doing the same thing over and over in different approaches or languages. In an architectural clash you will learn by **clashing with the existent codebase** while you try to change it drastically. Take a monolithic backend application, try to convert everything in a microservice architecture. Obviously you can't do that. But You should ask: **"Why can't I do it?"**. Doing that you will expose a lot of problem of your codebase and after the clash you can work on them to gradually solve them.
